### ISSUE TITLE
Is there a way to skip the new alpenglow theme?

### ISSUE THREAD

**Issue by YKZarb** [drsjb80/oldthematic#3]
The new alpenglow theme that has been added cannot be deleted. Even when I disable it, it shows up the next time its turn comes up in the rotation. Is there a way to prevent it from inserting itself in the rotation of themes I chose?

**Comment by drb80** [comment]
We'll take a look and probably put it on the default list so it won't be in the rotation. Thanks for the report!

**Comment by drb80** [comment]
Version 6.0.2 posted; let us know if that fixes it for you. Thanks!

**Comment by YKZarb** [comment]
Yes. It appears to have worked! Thank you. I much prefer my own theme collections to choose from.


     On Monday, September 28, 2020, 09:43:27 AM PDT, Steve Beaty <notifications@github.com> wrote:  
 
 


Version 6.0.2 posted; let us know if that fixes it for you. Thanks!

**Comment by drsjb80** [comment]
Great! I'll close this issue.
